#!/usr/bin/env node
// Builds pipeline/harness/harness-data.js: the three TS modules (type-stripped with Node's built-in
// module.stripTypeScriptTypes, no bundler) plus fx-data.json, as ONE classic script that exposes
// window.MB = { art, font, baker, fxData }. Classic script = the harness opens from file:// directly.
//   node pipeline/harness/build.mjs          (Node >= 22.13 / 23.2)
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { stripTypeScriptTypes } from "node:module";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..", "..");

function asIife(file) {
  const src = fs.readFileSync(file, "utf8");
  let js = stripTypeScriptTypes(src, { mode: "strip" });
  if (/^\s*import\s[^;]*from\s/m.test(js)) throw new Error(`${file}: runtime import left after stripping; harness modules must be import-free`);
  const names = [...js.matchAll(/^export\s+(?:const|let|var|function|class)\s+([A-Za-z_$][\w$]*)/gm)].map((m) => m[1]);
  js = js.replace(/^export\s+(?=const|let|var|function|class)/gm, "");
  return `(() => {\n${js}\nreturn { ${names.join(", ")} };\n})()`;
}

const out = `// GENERATED by pipeline/harness/build.mjs from art/sprites.ts, pipeline/pixel-font.ts,
// pipeline/texture-baker.ts and pipeline/fx-data.json. Do not edit; rerun the build.
window.MB = {
  art: ${asIife(path.join(root, "art", "sprites.ts"))},
  font: ${asIife(path.join(root, "pipeline", "pixel-font.ts"))},
  baker: ${asIife(path.join(root, "pipeline", "texture-baker.ts"))},
  fxData: ${fs.readFileSync(path.join(root, "pipeline", "fx-data.json"), "utf8")},
};
`;
fs.writeFileSync(path.join(here, "harness-data.js"), out);
console.log(`wrote pipeline/harness/harness-data.js (${(out.length / 1024).toFixed(0)} KiB)`);
