#!/usr/bin/env python3
"""עוד סבב art pipeline: one command from the DCC sources to what Godot loads.

  python3 pipeline/od-sevev/build.py              refs -> render -> drift check -> import sprites + font + proofs
  python3 pipeline/od-sevev/build.py --no-render  import the approved showcase out/ as-is (about 5 s)
  python3 pipeline/od-sevev/build.py --godot      also run Godot's import, measure the .ctex bytes the
                                                  web .pck will carry, and render the font specimen through
                                                  Godot's TextServer (opens a small window for ~2 s)
  --allow-drift   import a render whose pixels differ from the approved out/ (default: fail)

Also imports the 2D Artist's UI kit (art/od-sevev/ui-kit.json) and app-icon master as-is.

Sources (read only): the creative pack at $ODS_CREATIVE_PACK, default
  gamestudio/output/artifacts/creative-pack/od-sevev/  (art/refs, art/showcase/src, art/src).
Outputs: game/assets/sprites/**, game/assets/fonts/**, pipeline/od-sevev/proofs/**, budget.json.
Needs: python3 with Pillow and numpy; Godot 4.7.2 via tools/godot.sh for --godot.
"""
import argparse, glob, json, os, re, shutil, subprocess, sys, tempfile, time
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
sys.dont_write_bytecode = True          # keep __pycache__ out of the repo
sys.path.insert(0, HERE)
import font as F
import sprites as S

FORK = S.FORK
GAME = os.path.join(FORK, "game")
FONT_DEST = os.path.join(GAME, "assets", "fonts")
PROOFS = os.path.join(HERE, "proofs")
BMFONT_PARAMS = {"scaling_mode": "1", "compress": "true"}   # integer-only scaling; zstd the .fontdata (lossless)


def log(msg):
    print(msg, flush=True)


def build_font():
    font = F.parse()
    for line in F.check(font):
        log("font: " + line)
    # content coverage: every glyph the game's strings use (keys starting with "_" are docs)
    have = set(font["glyphs"]) | set(font["aliases"]) | set(font["zeros"]) | {0x20, 0x0A}

    def walk(o, path):
        if isinstance(o, str):
            yield path, o
        elif isinstance(o, dict):
            for k, v in o.items():
                if not str(k).startswith("_"):
                    yield from walk(v, f"{path}.{k}")
        elif isinstance(o, list):
            for i, v in enumerate(o):
                yield from walk(v, f"{path}[{i}]")
    for rel in ("ux/ui-strings.json", "design/content.json"):
        fp = os.path.join(FORK, rel)
        if not os.path.exists(fp):
            continue
        miss = {}
        for path, s in walk(json.load(open(fp, encoding="utf-8")), ""):
            for ch in s:
                if ord(ch) not in have:
                    miss.setdefault(ch, path)
        log(f"font: {rel}: " + ("every character covered" if not miss else
            "WARN no glyph for " + ", ".join(f"U+{ord(c):04X} {c!r} (e.g. {p})" for c, p in miss.items())))
    os.makedirs(FONT_DEST, exist_ok=True)
    stats = []
    for name, outline in (("sevev9", False), ("sevev9_outline", True)):
        st = F.build(font, FONT_DEST, name, outline)
        S.write_import(os.path.join(FONT_DEST, name + ".fnt"), "font_data_bmfont", "FontFile", BMFONT_PARAMS)
        stats.append(st)
        log(f"font: {name}.fnt + .png page {st['page'][0]}x{st['page'][1]}, {st['chars']} chars")

    # Sevev 9 @2: the density-2 companion (same box at half the scale; every metric exactly 2x)
    font2 = F.parse(F.SOURCE_2X, density=2)
    for line in F.check(font2):
        log("font @2: " + line)
    st = F.build(font2, FONT_DEST, FONT_2X, False)
    S.write_import(os.path.join(FONT_DEST, FONT_2X + ".fnt"), "font_data_bmfont", "FontFile", BMFONT_PARAMS)
    # the page is embedded in the .fontdata: never import it as a texture of its own (as Sevev 9's pages)
    open(os.path.join(FONT_DEST, FONT_2X + ".png.import"), "w").write('[remap]\n\nimporter="skip"\n')
    stats.append(st)
    log(f"font: {FONT_2X}.fnt + .png page {st['page'][0]}x{st['page'][1]}, {st['chars']} chars")
    metric = F.check_companion(os.path.join(FONT_DEST, "sevev9.fnt"), os.path.join(FONT_DEST, FONT_2X + ".fnt"), 2)
    for line in metric:
        log("font: " + line)
    write_font_manifest(stats, metric)
    return font, font2, stats


FONT_2X = "sevev9@2"


def write_font_manifest(stats, metric):
    """game/assets/fonts/fonts.json: every cut with its density, so the engine picks a cut by density and
    draws it at (logical px per Sevev 9 px) / density. Generated; never hand-edited."""
    by = {st["name"]: st for st in stats}
    entry = lambda n, **kw: {"file": n + ".fnt", "density": by[n]["density"], "size": by[n]["size"],
                             "lineHeight": by[n]["lineHeight"], "base": by[n]["base"], "chars": by[n]["chars"], **kw}
    man = {
        "_doc": "Generated by pipeline/od-sevev/build.py (CONTRACT.md §6). density = font px per Sevev 9 px: a "
                "density-d cut is drawn at (the Sevev 9 scale) / d and covers exactly the same box, because every "
                "xadvance, the line height, the baseline and every ink box are d x Sevev 9's (checked at build: "
                "metricCheck). Layout, string budgets and the text lint measure with Sevev 9 and hold for every cut.",
        "fonts": {
            "sevev9": entry("sevev9", outline="sevev9_outline.fnt", role="display: the chunky cut"),
            "sevev9_outline": entry("sevev9_outline", companionOf="sevev9", role="display over art (baked ink ring)"),
            FONT_2X: entry(FONT_2X, companionOf="sevev9", role="reading text: the sharp cut (same box)"),
        },
        "metricCheck": metric,
    }
    json.dump(man, open(os.path.join(FONT_DEST, "fonts.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=1)


# ------------------------------------------------------------------ proofs
def _text(img, font, text, x, y, scale, color=(255, 255, 255, 255)):
    """Proof-only LTR blitter (used for hex labels and Latin); Hebrew proofs go through Godot."""
    g, al, sp = font["glyphs"], font["aliases"], font["space"]
    for ch in text:
        cp = ord(ch)
        src = cp if cp in g else al.get(cp)
        if src in g:
            rows = g[src]
            for j, r in enumerate(rows):
                for i, c in enumerate(r):
                    if c == "#":
                        for dy in range(scale):
                            for dx in range(scale):
                                img.putpixel((x + (i) * scale + dx, y + j * scale + dy), color)
            x += (len(rows[0]) + 1) * scale
        else:
            x += (sp + 1) * scale


def proof_glyphs(font):
    g = font["glyphs"]
    cps = sorted(g)
    cols, cw, ch = 12, 58, 66
    rows = (len(cps) + cols - 1) // cols
    img = Image.new("RGBA", (cols * cw + 8, rows * ch + 8), (42, 35, 64, 255))
    for k, cp in enumerate(cps):
        x, y = 4 + (k % cols) * cw, 4 + (k // cols) * ch
        for yy in range(y, y + ch - 4):
            for xx in range(x, x + cw - 4):
                img.putpixel((xx, yy), (27, 20, 38, 255))
        # the glyph at x4 with its advance box
        gx, gy = x + 6, y + 4
        w = len(g[cp][0])
        for j, r in enumerate(g[cp]):
            for i, c in enumerate(r):
                col = (247, 244, 236, 255) if c == "#" else ((60, 52, 84, 255) if 2 <= j <= 6 else (44, 38, 62, 255))
                for dy in range(4):
                    for dx in range(4):
                        img.putpixel((gx + i * 4 + dx, gy + j * 4 + dy), col)
        _text(img, font, f"{cp:04X}", x + 4, y + 44, 2, (245, 197, 66, 255))
    p = os.path.join(PROOFS, "font-glyphs.png")
    img.save(p)
    return p


def proof_density_glyphs(font, font2, dp=4, d=2):
    """Every glyph, Sevev 9 at `dp` device px per px beside Sevev 9 @2 at dp/d, in the same advance box
    (the box shaded, the body band a shade lighter): the two halves of a cell must cover the same area."""
    g1, g2 = font["glyphs"], font2["glyphs"]
    cps = sorted(g1)
    cols = 8
    cw = 2 * 10 * dp + 24          # two cells of up to 9 + 1 px (the widest pictograms)
    ch = 9 * dp + 26
    rows = -(-len(cps) // cols)
    img = Image.new("RGBA", (cols * cw + 8, rows * ch + 8), (14, 10, 22, 255))
    ink, box, band = (247, 244, 236, 255), (44, 38, 62, 255), (60, 52, 84, 255)

    def cell(rows_, x0, y0, p, dens):
        w = len(rows_[0])
        adv = w + dens
        for j in range(9 * dens):
            col = band if 2 * dens <= j < 7 * dens else box
            img.paste(col, (x0, y0 + j * p, x0 + adv * p, y0 + (j + 1) * p))
        for j, r in enumerate(rows_):
            for i, c in enumerate(r):
                if c == "#":
                    img.paste(ink, (x0 + i * p, y0 + j * p, x0 + (i + 1) * p, y0 + (j + 1) * p))

    for k, cp in enumerate(cps):
        x, y = 4 + (k % cols) * cw, 4 + (k // cols) * ch
        img.paste((27, 20, 38, 255), (x, y, x + cw - 4, y + ch - 4))
        cell(g1[cp], x + 4, y + 4, dp, 1)
        cell(g2[cp], x + 4 + 10 * dp + 8, y + 4, dp // d, d)
        _text(img, font, f"{cp:04X}", x + 4, y + 9 * dp + 6, 2, (245, 197, 66, 255))
    return img


# The proof lines (logical order, as ui-strings / content write them): (caption, text, box width at x4, fg, bg)
DENSITY_LINES = [
    ("CHAT BUBBLE 104 ART", "אם זה לא עובר, אני עוזב. רגע, כבר עזבתי.", 416, "#ffffff", "#2e2250"),
    ("PRICE", "\u20662.51K\u2069\u00a0₪", 160, "#f5c542", "#1b1426"),
    ("TICKER", "תחקיר: לאן הולך הכסף? התשובה המלאה בעמוד \u206661\u2069. יש \u206660\u2069 עמודים.", 720, "#ffffff", "#7a1f2b"),
    ("SETTINGS LABEL", "תנועה מופחתת", 360, "#ffffff", "#1b1426"),
    ("SETTINGS CAPTION", "בלי טיקר רץ, בלי רעידות, בלי קפיצות.", 360, "#b8aecb", "#1b1426"),
    ("SETTINGS LABEL", "טקסט גדול", 360, "#ffffff", "#1b1426"),
    ("SETTINGS CAPTION", "לקריאה ממרחק זרוע.", 360, "#b8aecb", "#1b1426"),
    ("ALPHABET", "אבגדהוזחטיכךלמםנןסעפףצץקרשת", 720, "#ffffff", "#2a2340"),
    ("PAIRS", "ב כ · ד ר ך · ה ח ת · ו ז ן · ס ם · ע צ · מס׳ מסי", 720, "#ffffff", "#2a2340"),
    ("DIGITS", "0123456789 · \u2066+1.2K\u2069\u00a0₪ · 58/61 · ×14", 720, "#f5c542", "#2a2340"),
]

DENSITY_GD = r'''extends SceneTree
# Sevev 9 vs Sevev 9 @2 through Godot's TextServer at x4 logical on a k 4 device (1 logical = 1 device px):
# Sevev 9 at font_size 36 (9 x 4: a font px = 4 device px), @2 at font_size 36 (18 x 2: a font px = 2 device
# px). Each line is drawn in its real box (autowrap), then its shaped width is dumped for both cuts.
var vp: SubViewport
var frames := 0
func _initialize() -> void:
	var spec: Array = JSON.parse_string(FileAccess.get_file_as_string("res://lines.json"))
	var f1: FontFile = load("res://sevev9.fnt")
	var f2: FontFile = load("res://sevev9@2.fnt")
	for f in [f1, f2]:
		f.fixed_size_scale_mode = TextServer.FIXED_SIZE_SCALE_INTEGER_ONLY
		f.allow_system_fallback = false
	var W := int(spec[0]["canvasW"])
	var H := int(spec[0]["canvasH"])
	vp = SubViewport.new()
	vp.size = Vector2i(W, H)
	vp.transparent_bg = true
	vp.canvas_item_default_texture_filter = Viewport.DEFAULT_CANVAS_ITEM_TEXTURE_FILTER_NEAREST
	vp.render_target_update_mode = SubViewport.UPDATE_ALWAYS
	root.add_child(vp)
	var host := Control.new(); host.size = Vector2(W, H); vp.add_child(host)
	var dump := []
	for s in spec.slice(1):
		var row := {}
		for c in 2:
			var l := Label.new()
			l.add_theme_font_override("font", f1 if c == 0 else f2)
			l.add_theme_font_size_override("font_size", 36)
			l.add_theme_color_override("font_color", Color(s["fg"]))
			l.add_theme_constant_override("line_spacing", 0)
			l.text_direction = Control.TEXT_DIRECTION_RTL
			l.horizontal_alignment = HORIZONTAL_ALIGNMENT_RIGHT
			l.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
			l.text = s["text"]
			l.position = Vector2(s["x"][c], s["y"] + 4)
			l.size = Vector2(s["w"], 44)
			host.add_child(l)
			var ts := TextServerManager.get_primary_interface()
			var rid := ts.create_shaped_text(TextServer.DIRECTION_RTL)
			ts.shaped_text_add_string(rid, s["text"], (f1 if c == 0 else f2).get_rids(), 9 if c == 0 else 18)
			row["w%d" % (c + 1)] = ts.shaped_text_get_width(rid)
			ts.free_rid(rid)
		dump.append(row)
	FileAccess.open("res://widths.json", FileAccess.WRITE).store_string(JSON.stringify(dump))
func _process(_d: float) -> bool:
	frames += 1
	if frames == 4:
		vp.get_texture().get_image().save_png("res://lines.png")
		return true
	return false
'''


def proof_density(font, font2, with_godot):
    """proofs/font-density2.png: every glyph at x4 on a k 4 device (Sevev 9 = 4-dp px, @2 = 2-dp px), and,
    with --godot, the real strings through TextServer in their real boxes. Returns (path, width report)."""
    grid = proof_density_glyphs(font, font2)
    pad, colw = 16, 0
    rows, lines_img, widths = [], None, []
    if with_godot:
        # layout: per line a caption, then the Sevev 9 box and the @2 box side by side (both the real box width)
        def n_lines(text, w):                        # greedy word wrap at x4, for the box height only
            n, cur = 1, 0
            for word in text.split(" "):
                ww = F.advance_of(font, word) * 4
                nxt = ww if cur == 0 else cur + 16 + ww
                if nxt > w and cur:
                    n, cur = n + 1, ww
                else:
                    cur = nxt
            return n
        colw = max(w for _, _, w, _, _ in DENSITY_LINES)
        y = 0
        spec = []
        for cap, text, w, fg, bg in DENSITY_LINES:
            h = 44 * n_lines(text, w) + 8
            spec.append({"text": text, "w": w, "fg": fg, "bg": bg, "cap": cap, "y": y + 22, "h": h,
                         "x": [pad, pad + colw + 2 * pad]})
            y += 22 + h + 12
        W, H = pad * 4 + 2 * colw, y
        tmp = tempfile.mkdtemp(prefix="ods-density-")
        for f in os.listdir(FONT_DEST):
            if f.startswith("sevev9") and f.endswith((".fnt", ".png", ".import")):
                shutil.copy(os.path.join(FONT_DEST, f), tmp)
        for f in os.listdir(tmp):
            if f.endswith(".import"):
                txt = open(os.path.join(tmp, f)).read()
                txt = "\n".join(l for l in txt.split("\n") if not l.startswith(("uid=", "path=", "dest_files=", "source_file=")))
                open(os.path.join(tmp, f), "w").write(txt)
        open(os.path.join(tmp, "project.godot"), "w").write(
            'config_version=5\n[application]\nconfig/name="density"\n[display]\nwindow/size/viewport_width=64\n'
            'window/size/viewport_height=64\n[rendering]\nrenderer/rendering_method="gl_compatibility"\n'
            'textures/canvas_textures/default_texture_filter=0\n')
        json.dump([{"canvasW": W, "canvasH": H}] + spec, open(os.path.join(tmp, "lines.json"), "w"), ensure_ascii=False)
        open(os.path.join(tmp, "density.gd"), "w").write(DENSITY_GD)
        godot(["--headless", "--path", tmp, "--import"])
        r = godot(["--path", tmp, "--rendering-driver", "opengl3", "-s", "res://density.gd"], timeout=120)
        out = os.path.join(tmp, "lines.png")
        if not os.path.exists(out):
            raise RuntimeError("density proof render failed:\n" + r.stdout[-3000:] + r.stderr[-3000:])
        fg_img = Image.open(out).convert("RGBA")
        lines_img = Image.new("RGBA", (W, H), (14, 10, 22, 255))
        for s in spec:
            for c in range(2):
                x = s["x"][c]
                lines_img.paste(Image.new("RGBA", (s["w"], s["h"]), s["bg"]), (x, s["y"]))
            _text(lines_img, font, s["cap"], pad, s["y"] - 18, 2, (245, 197, 66, 255))
            _text(lines_img, font, "SEVEV 9 @2", s["x"][1], s["y"] - 18, 2, (245, 197, 66, 255))
        lines_img.alpha_composite(fg_img)
        widths = json.load(open(os.path.join(tmp, "widths.json")))
        shutil.rmtree(tmp, ignore_errors=True)
    W = max(grid.width, lines_img.width if lines_img else 0) + 16
    H = 40 + grid.height + (lines_img.height + 40 if lines_img else 0)
    sheet = Image.new("RGBA", (W, H), (14, 10, 22, 255))
    _text(sheet, font, "SEVEV 9 (4 DP PX) | SEVEV 9 @2 (2 DP PX) - X4 LOGICAL ON A K 4 DEVICE, SAME BOXES", 8, 12, 2,
          (247, 244, 236, 255))
    sheet.alpha_composite(grid, (8, 40))
    if lines_img:
        sheet.alpha_composite(lines_img, (8, 40 + grid.height + 32))
    p = os.path.join(PROOFS, "font-density2.png")
    sheet.save(p)
    return p, widths


def _frame(tex, spec, i=0):
    """Frame i of a strip or grid (sprites.json layout; `frameMap` picks the texture cell)."""
    cols = spec.get("cols", spec.get("frames", 1))
    fw, fh = spec["frameW"], spec["frameH"]
    c = spec["frameMap"][i] if "frameMap" in spec else i
    x, y = (c % cols) * fw, (c // cols) * fh
    return tex.crop((x, y, x + fw, y + fh))


def pick(entry, k):
    """SpriteStrip.pick_variant in Python: the render (main or a `densities` alternate) with the largest
    density dividing k, merged over the main entry; the main render when none divides k."""
    best, best_d = entry, (entry.get("density", 1) if k % entry.get("density", 1) == 0 else 0)
    for dk, alt in entry.get("densities", {}).items():
        if k % int(dk) == 0 and int(dk) > best_d:
            best, best_d = {**{x: y for x, y in entry.items() if x != "densities"}, **alt, "density": int(dk)}, int(dk)
    return best


def proof_cast(manifest, Z=3, k=None, name="sprites-contact.png"):
    """Everything on one sheet at ART x Z (a density-d texture at Z/d per sprite px), so the cast's 3x
    detail and the 1x stage, props and UI sit on one grid, the way the renderer will draw them.
    k: draw each character and source as SpriteStrip picks it for device scale k (Z = k = 4: the d 2
    alternates, as a DPR-2 phone draws them)."""
    D_ = S.DEST
    load = lambda sid: Image.open(os.path.join(D_, sid + ".png")).convert("RGBA")
    up = lambda im, d: im.resize((im.width * Z // d, im.height * Z // d), Image.NEAREST)
    chars = {n: (pick(c, k) if k else c) for n, c in manifest["chars"].items()}
    per_row, cell_w, cell_h = 8, 90 * Z, 150 * Z
    rows = -(-len(chars) // per_row)
    W = 180 * Z + 8 * Z + per_row * cell_w
    Hh = max(320 * Z, rows * cell_h) + 60 * Z
    img = Image.new("RGBA", (W, Hh), (27, 20, 38, 255))
    img.alpha_composite(up(load(manifest["stages"]["balfour"]["sprite"]), 1), (0, 0))
    b = chars.get("bibi")
    if b:
        d = b["density"]
        fr = up(_frame(Image.open(os.path.join(D_, b["anims"]["idle"]["texture"])).convert("RGBA"), {**b, **b["anims"]["idle"]}), d)
        fx, fy = manifest["magicianFeet"]
        img.alpha_composite(fr, (fx * Z - b["anchor"][0] * Z // d, fy * Z - b["anchor"][1] * Z // d))
    for k, (n, c) in enumerate(chars.items()):
        d = c["density"]
        cx = 180 * Z + 8 * Z + (k % per_row) * cell_w + cell_w // 2
        base = (k // per_row) * cell_h + 112 * Z
        fr = up(_frame(Image.open(os.path.join(D_, c["anims"]["idle"]["texture"])).convert("RGBA"), {**c, **c["anims"]["idle"]}), d)
        img.alpha_composite(fr, (cx - c["anchor"][0] * Z // d, base - c["anchor"][1] * Z // d))   # feet on one baseline
        if "avatar" in c:
            av = up(load(c["avatar"]), 1)
            img.alpha_composite(av, (cx - av.width // 2, base + 2 * Z))
    x, y = 4 * Z, max(320 * Z, rows * cell_h) + 4 * Z
    for sid, s in sorted(manifest.get("sources", {}).items()):
        s = pick(s, k) if k else s
        strip = load(s["sprite"])
        for i in range(2):
            fr = up(_frame(strip, s, i), s.get("density", 1))
            img.alpha_composite(fr, (x, y))
            x += fr.width + Z
        x += 6 * Z
    for sid in manifest["props"].values():
        im = up(load(sid), 1)
        img.alpha_composite(im, (x, y))
        x += im.width + 4 * Z
    p = os.path.join(PROOFS, name)
    img.save(p)
    return p


def proof_stage(manifest, Z=6, density=None, char="bibi", anim="crit", frame=6):
    """A character on the stage at ART xZ, the way SpriteStrip picks it for k = Z: the main render
    (d 3 at x6: sprite px x2) or a `densities` alternate (d 2 at x4: sprite px x2)."""
    D_ = S.DEST
    st = Image.open(os.path.join(D_, manifest["stages"]["balfour"]["sprite"] + ".png")).convert("RGBA")
    img = st.resize((180 * Z, 320 * Z), Image.NEAREST)
    c = manifest["chars"][char]
    if density is not None and density != c["density"]:
        c = {**c, **c["densities"][str(density)]}
    d = c["density"]
    fr = _frame(Image.open(os.path.join(D_, c["anims"][anim]["texture"])).convert("RGBA"), {**c, **c["anims"][anim]}, frame)
    fr = fr.resize((fr.width * Z // d, fr.height * Z // d), Image.NEAREST)
    fx, fy = manifest["magicianFeet"]
    img.alpha_composite(fr, (fx * Z - c["anchor"][0] * Z // d, fy * Z - c["anchor"][1] * Z // d))
    p = os.path.join(PROOFS, f"stage-x{Z}-{char}" + (f"-d{d}" if density is not None else "") + ".png")
    img.save(p)
    return p


# ------------------------------------------------------------------ Godot: import, bytes, specimen
GODOT = os.path.join(FORK, "tools", "godot.sh")

SPECIMEN_LINES = [
    "אבגדהוזחטיכךלמםנןסעפףצץקרשת",
    "עוד סבב",
    "סבב בחירות מס׳ 6. הציבור נרגש.",
    "⁦+1.2K⁩ ₪ לשנייה",
    "סגרנו · ⁦12,400⁩ ₪",
    "מע״מ 18%* · סה״כ · יועמ״ש · ו־3",
    "הליכוד ← עוצמה יהודית",
    "(בית המשפט) [טיוטה] {שם}",
    "לא יהיה כלום כי אין כלום…",
    "DOHA · OK · 1.2K 3M 4B 5T · +12 − 3 × 2 = 30",
    "#$&@\\^_`|~;:!? 0123456789 – —",
]

SPECIMEN_GD = r'''extends SceneTree
# Renders the Sevev 9 specimen through Godot's TextServer (bidi, per-glyph advances) and dumps
# each line's VISUAL glyph order (the glyph actually drawn, so mirrored brackets show as such)
# so direction is verified as data, not by eye.
var vp: SubViewport
var frames := 0
func _label(host: Control, font: FontFile, size: int, text: String, y: int, color: Color, x := 12, w := 736) -> void:
	var l := Label.new()
	l.add_theme_font_override("font", font)
	l.add_theme_font_size_override("font_size", size)
	l.add_theme_color_override("font_color", color)
	l.text_direction = Control.TEXT_DIRECTION_RTL          # the paragraph is RTL (bidi base level 1)
	l.horizontal_alignment = HORIZONTAL_ALIGNMENT_RIGHT
	l.text = text
	l.position = Vector2(x, y)
	l.size = Vector2(w, size * 11 / 9)
	host.add_child(l)
func _initialize() -> void:
	var lines: Array = JSON.parse_string(FileAccess.get_file_as_string("res://lines.json"))
	var plain: FontFile = load("res://sevev9.fnt")
	var outl: FontFile = load("res://sevev9_outline.fnt")
	vp = SubViewport.new()
	vp.size = Vector2i(760, 1320)
	vp.canvas_item_default_texture_filter = Viewport.DEFAULT_CANVAS_ITEM_TEXTURE_FILTER_NEAREST
	vp.render_target_update_mode = SubViewport.UPDATE_ALWAYS
	root.add_child(vp)
	var host := Control.new(); host.size = Vector2(760, 1320); vp.add_child(host)
	var bg := ColorRect.new(); bg.color = Color("#2a2340"); bg.size = host.size; host.add_child(bg)
	var y := 10
	for sp in [[18, lines.size()], [27, 5], [36, 3]]:
		for i in sp[1]:
			_label(host, plain, sp[0], lines[i], y, Color.WHITE)
			y += sp[0] * 11 / 9 + 2
		y += 10
	var st := TextureRect.new(); st.texture = load("res://stage.png"); st.position = Vector2(200, y)
	st.scale = Vector2(2, 2); host.add_child(st)
	_label(host, outl, 45, "עוד סבב!", y + 40, Color("#f5c542"), 200, 360)
	_label(host, outl, 27, "סבב בחירות מס׳ 6", y + 110, Color.WHITE, 200, 360)
	_label(host, plain, 18, "\u2066+1.2K\u2069\u00a0₪ לשנייה", y + 150, Color("#f5c542"), 200, 360)
	var ts := TextServerManager.get_primary_interface()
	var dump := []
	for s in lines:
		var rid := ts.create_shaped_text(TextServer.DIRECTION_RTL)
		ts.shaped_text_add_string(rid, s, plain.get_rids(), 9)
		var vis := ""
		var w := 0.0
		var tofu := 0
		for g in ts.shaped_text_get_glyphs(rid):
			w += g["advance"]
			var idx: int = g["index"]
			if not (g["font_rid"] as RID).is_valid():
				var c: int = String(s).unicode_at(g["start"])
				if c > 0x20 and not (c >= 0x2066 and c <= 0x2069) and c != 0xA0:
					tofu += 1
					vis += "□"
				continue
			vis += String.chr(idx) if idx > 0x20 else " "
		dump.append({"visual": vis, "width": w, "tofu": tofu})
		ts.free_rid(rid)
	FileAccess.open("res://visual.json", FileAccess.WRITE).store_string(JSON.stringify(dump))
	print("server: ", ts.get_name())
func _process(_d: float) -> bool:
	frames += 1
	if frames == 4:
		vp.get_texture().get_image().save_png("res://specimen.png")
		return true
	return false
'''


def godot(args, cwd=None, timeout=300):
    return subprocess.run([GODOT] + args, cwd=cwd, capture_output=True, text=True, timeout=timeout)


def godot_import():
    r = godot(["--headless", "--path", GAME, "--import"], timeout=600)
    if r.returncode != 0:
        raise RuntimeError("godot --import failed:\n" + r.stdout[-2000:] + r.stderr[-2000:])


def measure(manifest):
    """Bytes the web .pck carries for our assets: the imported .ctex/.fontdata files."""
    rows = []
    roots = [(S.DEST, "sprites"), (FONT_DEST, "fonts")]
    for root, label in roots:
        for ip in sorted(glob.glob(os.path.join(root, "**", "*.import"), recursive=True)):
            if not os.path.exists(ip[:-len(".import")]):   # an orphan .import (its PNG was retired): drop it
                os.remove(ip)
                continue
            txt = open(ip).read()
            if 'importer="skip"' in txt:      # a BMFont page: Godot embeds it in the .fontdata
                rows.append({"file": os.path.relpath(ip[:-len(".import")], GAME), "source": os.path.getsize(ip[:-7]),
                             "imported": 0, "note": "embedded in the .fontdata"})
                continue
            m = re.search(r'dest_files=\["res://([^"]+)"', txt)
            src = ip[:-len(".import")]
            dst = os.path.join(GAME, m.group(1)) if m else None
            rows.append({"file": os.path.relpath(src, GAME), "source": os.path.getsize(src),
                         "imported": os.path.getsize(dst) if dst and os.path.exists(dst) else None})
    return rows


def specimen(font_dir):
    tmp = tempfile.mkdtemp(prefix="ods-specimen-")
    for f in os.listdir(font_dir):
        if f.endswith((".fnt", ".png", ".import")):
            shutil.copy(os.path.join(font_dir, f), tmp)
    for f in os.listdir(tmp):          # drop Godot's uid/dest lines so the temp project re-imports cleanly
        if f.endswith(".import"):
            txt = open(os.path.join(tmp, f)).read()
            txt = "\n".join(l for l in txt.split("\n") if not l.startswith(("uid=", "path=", "dest_files=", "source_file=")))
            open(os.path.join(tmp, f), "w").write(txt)
    shutil.copy(os.path.join(S.DEST, "stage_balfour.png"), os.path.join(tmp, "stage.png"))
    S.write_import(os.path.join(tmp, "stage.png"), "texture", "CompressedTexture2D", S.TEX_PARAMS)
    open(os.path.join(tmp, "project.godot"), "w").write(
        'config_version=5\n[application]\nconfig/name="specimen"\n[display]\nwindow/size/viewport_width=64\n'
        'window/size/viewport_height=64\n[rendering]\nrenderer/rendering_method="gl_compatibility"\n'
        'textures/canvas_textures/default_texture_filter=0\n')
    json.dump(SPECIMEN_LINES, open(os.path.join(tmp, "lines.json"), "w"), ensure_ascii=False)
    open(os.path.join(tmp, "specimen.gd"), "w").write(SPECIMEN_GD)
    r = godot(["--headless", "--path", tmp, "--import"])
    r = godot(["--path", tmp, "--rendering-driver", "opengl3", "-s", "res://specimen.gd"], timeout=120)
    out = os.path.join(tmp, "specimen.png")
    if not os.path.exists(out):
        raise RuntimeError("specimen render failed:\n" + r.stdout[-3000:] + r.stderr[-3000:])
    shutil.copy(out, os.path.join(PROOFS, "font-specimen-godot.png"))
    vis = json.load(open(os.path.join(tmp, "visual.json"), encoding="utf-8"))
    return os.path.join(PROOFS, "font-specimen-godot.png"), vis, r.stdout


# ------------------------------------------------------------------ main
def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--no-render", action="store_true")
    ap.add_argument("--allow-drift", action="store_true")
    ap.add_argument("--godot", action="store_true")
    a = ap.parse_args()
    t0 = time.time()
    os.makedirs(PROOFS, exist_ok=True)

    if a.no_render:
        src = S.APPROVED_OUT
        log(f"sprites: importing the approved out/ as-is: {src}")
    else:
        src = S.render(log)
        changed, new, old = S.drift(src)
        log(f"drift vs approved out/: {len(changed)} changed, {len(new)} new, {len(old)} only in approved")
        for f in new:
            log(f"  new (not yet in approved out/): {f}")
        for f in old:
            log(f"  only in approved out/ (no ref or cast.py entry renders it): {f}")
        if changed:
            msg = "rendered pixels differ from the approved look:\n  " + "\n  ".join(changed)
            if not a.allow_drift:
                raise SystemExit("FAIL " + msg + "\n(re-run with --allow-drift only if Bar approved the change)")
            log("WARN " + msg)

    refs = {os.path.basename(p): S.sha(p) for p in sorted(glob.glob(os.path.join(S.REFS, "*.png")))}
    provenance = {
        "refs": "ChatGPT reference images generated by Bar (conversation 'יצירת דמות בפיקסל ארט'), "
                "first-party; no third-party licence",
        "refShas": refs,
        "renderDown": "creative-pack art/showcase/src (rig.py, build.py, cast.py)",
        "stagesAndWordmark": "creative-pack art/src (locations.py, wordmark.py)",
        "renderedFrom": "refs" if not a.no_render else "approved out/",
    }
    manifest, warns = S.import_sprites(src, log, provenance)
    if not a.no_render:                       # the staging copy is disposable once imported
        shutil.rmtree(os.path.abspath(os.path.join(src, "..", "..", "..")), ignore_errors=True)
    bad = S.check_content_sources(manifest)
    if bad:
        raise SystemExit("FAIL content money sources that don't resolve to shipped art (design/content.json "
                         "producers[]):\n  " + "\n  ".join(bad))
    log("sources: every content money source resolves (stage strip, icon, silhouette, set-piece art)")
    icons = S.import_icons(log)
    log(f"sprites: {len(manifest['chars'])} characters, {len(manifest['props'])} props, "
        f"{len(manifest['stages'])} stages -> {S.DEST}")

    font, font2, fstats = build_font()
    log("proof: " + proof_glyphs(font))
    log("proof: " + proof_cast(manifest))
    log("proof: " + proof_cast(manifest, Z=4, k=4, name="sprites-contact-k4.png"))   # the d 2 renders, as k 4 draws them
    log("proof: " + proof_stage(manifest))
    for dk in manifest["chars"].get("bibi", {}).get("densities", {}):
        z = next(k for k in (4, 2, 8) if k % int(dk) == 0)      # the phone scale the alternate is for
        log("proof: " + proof_stage(manifest, Z=z, density=int(dk)))

    budget = {"sourceBytes": {}, "vramBytes": 0}
    for rel, f in manifest["files"].items():
        budget["sourceBytes"][f"sprites/{rel}"] = f["bytes"]
        budget["vramBytes"] += f["size"][0] * f["size"][1] * 4
    for st in fstats:
        p = os.path.join(FONT_DEST, st["name"] + ".png")
        budget["sourceBytes"][f"fonts/{st['name']}.png"] = os.path.getsize(p)
        budget["sourceBytes"][f"fonts/{st['name']}.fnt"] = os.path.getsize(os.path.join(FONT_DEST, st["name"] + ".fnt"))
        budget["vramBytes"] += st["page"][0] * st["page"][1] * 4

    # typical resident set (lazy per-character loading): the Magician's strips, one stage, the small Dubi,
    # every money source, the UI kit, avatars, props/FX and the fonts. Partners load when their scene opens.
    # SpriteStrip loads only the render pick_variant picks for the device's k, so one density of each
    # character (and, once the diorama picks too, of each source) is resident at a time: the budget is per k.
    def resident(rel):
        n = os.path.basename(rel)
        if n.startswith("source_") and not n.endswith(("_icon.png", "_icon_sil.png")) and rel in src_strips:
            return False                                   # the rendered sources' stage strips: per k, below
        return (n.startswith(("stage_balfour", "dubi_small_", "source_", "avatar", "prop_", "fx_"))
                or os.path.splitext(n)[0] in manifest["ui"])
    src_strips = {v["sprite"] + ".png" for s_ in manifest["sources"].values() if s_.get("origin") == "render-down"
                  for v in [s_] + list(s_.get("densities", {}).values())}
    tex = lambda rel: manifest["files"][rel]["size"][0] * manifest["files"][rel]["size"][1] * 4
    char_tex = lambda c: sum(tex(a["texture"]) for a in c["anims"].values() if a["texture"] in manifest["files"])
    budget["vramByDensity"] = {n: {str(v.get("density", 1)): char_tex({**c, **v}) for v in [c] + list(c.get("densities", {}).values())}
                               for n, c in manifest["chars"].items()}
    budget["vramBibi"] = budget["vramByDensity"].get("bibi", {})
    base = sum(tex(rel) for rel in manifest["files"] if resident(rel)) + sum(st["page"][0] * st["page"][1] * 4 for st in fstats)
    budget["vramTypicalByK"], budget["vramSourcesByK"], budget["vramPerPartnerByK"] = {}, {}, {}
    for k in (2, 3, 4, 6, 7, 8, 9):
        budget["vramSourcesByK"][str(k)] = sum(tex(pick(s_, k)["sprite"] + ".png") for s_ in manifest["sources"].values()
                                               if pick(s_, k)["sprite"] + ".png" in src_strips)
        budget["vramTypicalByK"][str(k)] = base + budget["vramSourcesByK"][str(k)] + char_tex(pick(manifest["chars"]["bibi"], k))
        budget["vramPerPartnerByK"][str(k)] = {n: char_tex(pick(c, k)) for n, c in manifest["chars"].items() if n != "bibi"}
    budget["vramTypical"] = max(budget["vramTypicalByK"].values())      # the worst k
    budget["vramCastAll"] = sum(tex(rel) for rel in manifest["files"] if rel.startswith("cast/"))
    budget["vramPerPartner"] = budget["vramPerPartnerByK"]["6"]          # the main (d 3) renders
    if a.godot:
        godot_import()
        rows = measure(manifest)
        budget["imported"] = rows
        budget["pckBytes"] = sum(r["imported"] or 0 for r in rows)
        imp = {r["file"]: r["imported"] or 0 for r in rows}
        budget["pckByAsset"] = {}                         # per rendered character / source: {density: .pck bytes}
        for n, c in manifest["chars"].items():
            budget["pckByAsset"][n] = {str(v["density"]): sum(imp.get("assets/sprites/" + t["texture"], 0) for t in v["anims"].values())
                                       for v in [c] + list(c.get("densities", {}).values())}
        for sid, s_ in manifest["sources"].items():
            budget["pckByAsset"]["source_" + sid] = {str(v["density"]): imp.get(f"assets/sprites/{v['sprite']}.png", 0)
                                                     for v in [s_] + list(s_.get("densities", {}).values())}
        missing = [r["file"] for r in rows if r["imported"] is None]
        if missing:
            raise SystemExit("FAIL Godot did not import: " + ", ".join(missing))
        # the import pass rewrote the .import files: re-assert our params (idempotent)
        for rel in manifest["files"]:
            S.write_import(os.path.join(S.DEST, rel), "texture", "CompressedTexture2D", S.TEX_PARAMS)
        for st in fstats:
            S.write_import(os.path.join(FONT_DEST, st["name"] + ".fnt"), "font_data_bmfont", "FontFile", BMFONT_PARAMS)
        p, vis, out = specimen(FONT_DEST)
        log("proof: " + p)
        budget["specimenVisual"] = vis
        tofu = [v["visual"] for v in vis if v["tofu"]]
        if tofu:
            raise SystemExit("FAIL tofu (missing glyph) in the Godot specimen: " + " | ".join(tofu))
        for line, v in zip(SPECIMEN_LINES, vis):
            exp = F.advance_of(font, line) + 1
            if abs(v["width"] / 1 - exp) > 0.01:
                log(f"WARN width mismatch '{line}': godot {v['width']} vs table {exp}")
        p, widths = proof_density(font, font2, True)
        log("proof: " + p)
        off = [(DENSITY_LINES[i][1], w) for i, w in enumerate(widths) if abs(w["w2"] - 2 * w["w1"]) > 0.01]
        if off:
            raise SystemExit("FAIL Sevev 9 @2 shaped width != 2 x Sevev 9 in TextServer: " + repr(off))
        log(f"font: TextServer shaped widths, {len(widths)} proof lines: @2 = 2 x Sevev 9 on every line")
        budget["densityProofWidths"] = widths
    else:
        log("proof: " + proof_density(font, font2, False)[0])

    budget["sourceTotal"] = sum(budget["sourceBytes"].values())
    json.dump(budget, open(os.path.join(HERE, "budget.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    log(f"budget: source {budget['sourceTotal']:,} B, VRAM typical {budget['vramTypical']:,} B "
        f"(by k {budget['vramTypicalByK']}; cast all {budget['vramCastAll']:,} B; "
        f"all resident {budget['vramBytes']:,} B)"
        + (f", web .pck {budget['pckBytes']:,} B" if "pckBytes" in budget else ""))
    log(f"done in {time.time() - t0:.1f}s" + (f" with {len(warns)} waived warnings" if warns else ""))


if __name__ == "__main__":
    main()
