class_name Tune
extends RefCounted
## Feel tunables (design/feel-spec.md §8) and Animator motion constants (motion/motion-spec.yaml,
## motion/object-motion.md). GENERATED from v1.1 src/core/tuning.ts + src/core/motion.ts by the v2 port;
## the spec docs stay the owners of these numbers. Access: Tune.T["squashScaleY"], Tune.MC["modalEnterMs"].

const FRAME_MS := 1000.0 / 60.0

const T := {
	"tapLatencyTargetFrames": 1,
	"tapLatencyCeilingFrames": 2,
	"squashScaleX": 1.12,
	"squashScaleY": 0.88,
	"squashMinScaleY": 0.84,
	"squashDownMs": 40,
	"squashReturnMs": 140,
	"squashReturnOvershoot": 2.2,
	"magicianHitPadPx": 16,
	"magicianHoverScale": 1.0,
	"magicianHoverHaloAlpha": 0.3,
	"magicianHoverMs": 100,
	"bankPopScale": 1.06,
	"bankPopMs": 80,
	"floaterJitterXPx": 24,
	"floaterRisePx": 88,
	"floaterRiseMs": 700,
	"floaterFadeStartMs": 400,
	"floaterTextHeightPx": 28,
	"floaterMaxConcurrent": 24,
	"tapChipCount": 3,
	"tapChipArcDeg": 180,
	"tapChipSpeed": 220,
	"chipGravity": 600,
	"tapChipLifeMs": 350,
	"tapHitStopFrames": 0,
	"critFloaterTextHeightPx": 42,
	"critFloaterPopScale": 1.3,
	"critFloaterPopMs": 120,
	"critFloaterRisePx": 120,
	"critFloaterRiseMs": 900,
	"critShakePx": 3,
	"critShakeMs": 100,
	"critChipCount": 10,
	"critChipSpeed": 320,
	"critChipLifeMs": 450,
	"reducedMotionChipFactor": 0.5,
	"goldenSpawnXMin": 0.12,
	"goldenSpawnXMax": 0.88,
	"goldenSpawnYMin": 0.20,
	"goldenSpawnYMax": 0.50,
	"goldenMagicianExclusion": 0.25,
	"goldenSpawnMaxTries": 20,
	"goldenHitRadiusPx": 56,
	"goldenFadeInMs": 300,
	"goldenSpawnStartScale": 0.6,
	"goldenBobPx": 8,
	"goldenBobHz": 1.2,
	"goldenWobbleDeg": 8,
	"goldenWobbleHz": 0.8,
	"goldenDriftSpeed": 18,
	"goldenBlinkLastMs": 2000,
	"goldenBlinkHz": 6,
	"goldenBlinkMinAlpha": 0.35,
	"goldenDespawnFadeMs": 200,
	"goldenCatchPopScale": 1.5,
	"goldenCatchPopMs": 150,
	"goldenBurstCount": 16,
	"goldenBurstSpeed": 360,
	"goldenBurstLifeMs": 600,
	"goldenCatchShakePx": 4,
	"goldenCatchShakeMs": 150,
	"buffBannerHoldMs": 1600,
	"buffBannerFadeMs": 200,
	"frenzyEdgePulseHz": 2,
	"tapFrenzyGlowStaticUnderReducedMotion": true,
	"tapFrenzyGlowPulseHz": 3,
	"buyPressScale": 0.95,
	"buyPressMs": 60,
	"buyReleaseMs": 80,
	"buyDragCancelPx": 10,
	"buyFlashAlpha": 0.6,
	"buyFlashMs": 80,
	"ownedPopScale": 1.25,
	"ownedPopMs": 150,
	"iconHopPx": 8,
	"iconHopMs": 120,
	"upgradePopScale": 1.3,
	"upgradePopMs": 200,
	"shelfReflowMs": 150,
	"cantAffordShakePx": 4,
	"cantAffordShakeCycles": 3,
	"cantAffordShakeMs": 180,
	"holdRepeatDelayMs": 400,
	"holdRepeatIntervalMs": 100,
	"affordGlintMs": 250,
	"affordGlintCooldownMs": 5000,
	"minRowHeightPx": 96,
	"evolveFadeOutMs": 400,
	"evolveTitleCardMs": 800,
	"evolveFadeInMs": 300,
	"offlineRollMs": 800,
	"tickerScrollSpeed": 90,
	"headlineFlashMs": 120,
}

const MC := {
	"uiPressMinHoldMs": 60,
	"uiLabelPressDropArtPx": 2,
	"modalEnterMs": 240,
	"modalExitMs": 160,
	"modalExitOffsetPx": 32,
	"backdropAlpha": 0.6,
	"tabSwitchOutMs": 60,
	"tabSwitchInMs": 140,
	"tabSwitchOffsetPx": 32,
	"evolveRevealPopMs": 170,
	"evolveRevealGlintDelayMs": 300,
	"evolveReadyPeriodMs": 3000,
	"evolveReadyGlowMs": 600,
	"luckyBunchRollMs": 500,
	"bannerEnterOffsetPx": 16,
	"buffEndWarnMs": 3000,
	"buffEndBlinkHz": 2,
	"headlineDeferAfterEvolveMs": 300,
	"bbBobHalfMs": 1600,
	"bbBobHalfFrenzyMs": 800,
	"bbBobResumeMs": 600,
	"bbBobPx": 5,
	"bbFidgetMinMs": 6000,
	"bbFidgetMaxMs": 9000,
	"bbFidgetFrameMs": 80,
	"critFlashMs": 33,
	"critterPlopFallPx": 32,
	"critterPlopMs": 120,
	"critterLandHoldMs": 100,
	"critterPlopThrottleMs": 100,
	"critterBulkStaggerMs": 60,
	"critterHopMs": 200,
	"critterWanderMinMs": 4000,
	"critterWanderMaxMs": 9000,
	"critterHopGlobalGapMs": 250,
	"critterReducedFadeMs": 150,
	"cloudStepPx": 4,
	"cloudStepMs": 750,
	"listMomentumDecay": 0.92,
	"listMomentumStop": 0.1,
	"wheelNotchPx": 104,
	"wheelEaseMs": 120,
	"revealAutoScrollMs": 250,
	"revealAutoScrollIdleMs": 2000,
	"thumbIdleMs": 1000,
	"thumbIdleAlpha": 0.4,
	"ftueHandBobPx": 8,
	"ftueHandBobHz": 1,
	"titleCtaPulseHz": 1,
	"titleFadeMs": 300,
	"titleFadeReducedMs": 150,
	"offlineEndBeatMs": 60,
	"offlineCloseAfterRollMs": 300,
	"tickerPageMs": 3000,
	"tickerPageChars": 33,
	"tickerGapPx": 48,
	"squishPx": 8,
	"squishReboundMs": 67,
	"bankGainPopMs": 117,
	"bankGainTintMs": 200,
	"bpsHopPx": 6,
	"bpsTintHoldMs": 200,
	"cascadeStepMs": 50,
	"cascadeReach": 2,
	"cascadeMinGapMs": 250,
	"cascadeHopPx": 4,
	"reflowLandBumpPx": 4,
	"reflowIconStaggerMs": 40,
	"pillHelloMs": 167,
	"pillNudgePeriodMs": 4000,
	"pillNudgeIdleMs": 3000,
	"pillNudgeRepeatMs": 8000,
	"badgePopCooldownMs": 600,
	"dropInOffsetPx": 64,
	"tabListOvershootPx": 4,
	"tickerHopPx": 6,
	"tickerHopEntryInsetPx": 24,
	# od-sevev, mirrored verbatim from motion/motion-spec.yaml motion-constants (Animator-owned).
	# Only the constants the engine reads today; the rest land with the code that reads them.
	"coinBurstBase": 3,
	"coinBurstCap": 6,
	"critCoinBase": 10,
	"critCoinCap": 12,
}

## Critter idle frame durations (object-motion.md §3), wandering and set pieces.
## od-sevev: these are per-producer content fields (producers[].idleFrameMs, .wander, .setPiece);
## the FORK_* tables are the defaults for the fork's own ids, so old content behaves as before.
const FORK_CRITTER_FRAME_MS := {
	"intern": 500,
	"hardhat": 500,
	"bureaucrat": 500,
	"timechimp": 500,
	"tree": 667,
	"catapult": 1000,
	"moon": 1000,
	"rocket": 250,
}
const FORK_WANDERING := ["intern", "hardhat", "bureaucrat", "timechimp"]
const FORK_SET_PIECES := {"catapult": "lob", "rocket": "launch", "timechimp": "blink", "moon": "bob"}
## setPiece values the diorama knows: lob (throws a coin across the sky), launch (rises out of
## frame), blink (flickers and reappears nearby), bob (floats in place).
const SET_PIECES := ["lob", "launch", "blink", "bob"]
const DEFAULT_CRITTER_FRAME_MS := 500


static func critter_frame_ms(id: String) -> float:
	return float(Content.producer(id).get("idleFrameMs", FORK_CRITTER_FRAME_MS.get(id, DEFAULT_CRITTER_FRAME_MS)))


static func critter_wanders(id: String) -> bool:
	return bool(Content.producer(id).get("wander", FORK_WANDERING.has(id)))


## "" when the producer has no set piece.
static func set_piece(id: String) -> String:
	var v := String(Content.producer(id).get("setPiece", FORK_SET_PIECES.get(id, "")))
	return v if SET_PIECES.has(v) else ""
