#!/usr/bin/env python3
"""Generates game/scripts/ui/sevev_glyphs.gd, the engine's STAND-IN Hebrew pixel font, from the
2D Artist's approved draft (creative-pack art/src/hebfont.py, "Sevev 5x9").

The shipping font is the Technical Artist's BMFont in game/assets/fonts/ (HeFont prefers it the
moment it exists). This stand-in keeps Hebrew rendering through the real TextServer route until
then, and gives tests/unit/test_bidi.gd a font to shape with.

    python3 tools/gen_sevev_glyphs.py [path/to/hebfont.py]
"""
import importlib.util
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))
DEFAULT = os.path.normpath(os.path.join(ROOT, "..", "..", "artifacts", "creative-pack", "od-sevev", "art", "src", "hebfont.py"))
OUT = os.path.join(ROOT, "game", "scripts", "ui", "sevev_glyphs.gd")


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else DEFAULT
    sys.path.insert(0, os.path.dirname(src))   # hebfont imports pix
    spec = importlib.util.spec_from_file_location("hebfont", src)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    lines = [
        "class_name SevevGlyphs",
        "extends RefCounted",
        "## GENERATED by tools/gen_sevev_glyphs.py from the creative pack's art/src/hebfont.py",
        "## (\"Sevev 5x9\"). Do not edit: regenerate. The engine's stand-in until the Technical Artist's",
        "## BMFont lands in res://assets/fonts/ (HeFont picks that up first).",
        "## Rows: 2 ascender + 5 body + 2 descender; baseline under row 6 (ascent 7); '#' = ink.",
        "",
        "const CELL_H := 9",
        "const ASCENT := 7",
        "const LINE_H := %d" % mod.LINE_H,
        "const SPACE_ADVANCE := %d" % (mod.SPACE_W + 1),
        "const GLYPHS := {",
    ]
    for ch in sorted(mod.GLYPHS):
        rows = mod.GLYPHS[ch]
        key = ch.encode("unicode_escape").decode("ascii") if ord(ch) > 126 else ch
        key = key.replace("\\", "\\\\") if ord(ch) <= 126 else key
        if ch == '"':
            key = '\\"'
        lines.append('\t"%s": [%s],' % (key if ord(ch) <= 126 else "\\u%04x" % ord(ch), ", ".join('"%s"' % r for r in rows)))
    lines.append("}")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %s (%d glyphs)" % (os.path.relpath(OUT, ROOT), len(mod.GLYPHS)))


if __name__ == "__main__":
    main()
